### ISSUE TITLE
failing travis and plugin pre check reports

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-mod_panopto#1]
The plugins db precheck report shows a number of failures that would be good to fix (these are also picked up by travis.) - This is not necessarily a blocker for approval in the plugins db, but at a minimum it would be nice not to see any of these errors:
* Expected MOODLE_INTERNAL check or config.php inclusion

**Comment by kabalin** [comment]
Thanks Dan for spending time reviewing it. I addressed most code style issues at https://github.com/lucisgit/moodle-mod_panopto/commit/a3fa84cbd9cdb9df0f6edce0c59fb9d9d731a704
