### ISSUE TITLE
Camel case

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-mod_panopto#3]
$string['chooseavideo'] = 'Choose Panopto Video';

should be
$string['chooseavideo'] = 'Choose Panopto video';

**Comment by kabalin** [comment]
Well spotted, thanks Dan! Issue has been addressed at https://github.com/lucisgit/moodle-mod_panopto/commit/a3fa84cbd9cdb9df0f6edce0c59fb9d9d731a704
