### ISSUE TITLE
panoptogroupid field missing from backup_panopto_stepslib.php

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-mod_panopto#4]
should panopto_user_access be part of the backups too?

**Comment by kabalin** [comment]
Nope, this table is designed to keep temporary records when access has been granted (so no extra API calls made within timeout window), then they are removed after "timeout" (and will be granted access again if they request it, will be added to table and then removed after timeout, and so on). More info here: https://github.com/lucisgit/moodle-mod_panopto#what-happens-under-the-bonnet
