### ISSUE TITLE
Circular dependency between Panopto mod and repository plugins

### ISSUE THREAD

**Issue by logan-reynolds** [lucisgit/moodle-mod_panopto#6]
A circular dependency exists between components mod_panopto and repository_panopto with each component marking the other as a dependency in version.php, which makes these both unable to be uninstalled via the Moodle Plugins Overview page.  Only one plugin should declare the other as a dependency in it's version.php file, that way the first plugin can be uninstalled and then the dependency plugin can be uninstalled.  From reading the description it appears that the repository is used within the module and therefore depends on it, so the additional dependency should probably be removed from the module I'm guessing - either way is fine as long as the circular dependency is removed.

**Comment by kabalin** [comment]
Thanks for report @logan-reynolds, it is an important thing.
