### ISSUE TITLE
Installing without the panopto repository results in moodle not loading

### ISSUE THREAD

**Issue by devnoot** [lucisgit/moodle-mod_panopto#7]
When installing this plugin without the Panopto repository plugin, Moodle will not load, and throw a `500` error.

Here is the error, a simple check before requiring the repository file should fix it.
`
[Thu Jul 30 11:40:29.775483 2020] [proxy_fcgi:error] [pid 2979:tid 140107160332032] [client 130.58.6.121:20666] AH01071: Got error 'PHP message: PHP Warning:  require_once(/opt/moodle/moodle/repository/panopto/locallib.php): failed to open stream: No such file or directory in /opt/moodle/moodle/mod/panopto/lib.php on line 28\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/opt/moodle/moodle/repository/panopto/locallib.php' (include_path='/opt/moodle/moodle/lib/pear:.:/opt/rh/rh-php72/root/usr/share/pear:/opt/rh/rh-php72/root/usr/share/php') in /opt/moodle/moodle/mod/panopto/lib.php on line 28\n'
`

**Comment by kabalin** [comment]
Hi @devnoot, This plugin will not work without Panopto repository, it is using to allow you to select video for this activity.  Please refer to Installation manual for more details: https://github.com/lucisgit/moodle-mod_panopto#installation
